name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libeigen3-dev

    - name: Install Google Test
      run: |
        sudo apt-get install -y libgtest-dev
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: Install yaml-cpp
      run: |
        sudo apt-get install -y libyaml-cpp-dev

    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Run Tests
      run: |
        cd build
        ctest --verbose
