# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up C++ environment
      uses: actions/setup-cpp@v1
      with:
        compiler: 'gcc' # or 'clang'
        build-type: 'Release'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libeigen3-dev

    - name: Install Google Test
      run: |
        sudo apt-get install -y cmake
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build && cd build
        cmake .. -DBUILD_GMOCK=OFF
        make
        sudo make install

    - name: Build
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

    - name: Run Tests
      run: |
        cd build
        ctest --verbose
